package com.generator.monitoring.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class DeviceDataMessage {
    private TelemetryData telemetry;
    private List<AlarmData> backendAlarms; // Alarms generated by backend threshold checks
}
